// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1v2b89pnSmnx4EySVy7-VSHQk9x7Cv_w',
    appId: '1:745744612072:web:319f9c53384db3ce31675d',
    messagingSenderId: '745744612072',
    projectId: 'pairtrack',
    authDomain: 'pairtrack.firebaseapp.com',
    storageBucket: 'pairtrack.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiBSzawhp4Dsxads6d1C6b3zIKAzscYlk',
    appId: '1:745744612072:android:2232236762c5071831675d',
    messagingSenderId: '745744612072',
    projectId: 'pairtrack',
    storageBucket: 'pairtrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH7mFd0fLZ-Isl1MWNFKFPpEA6whR0V8U',
    appId: '1:745744612072:ios:8710bc5a4b294fff31675d',
    messagingSenderId: '745744612072',
    projectId: 'pairtrack',
    storageBucket: 'pairtrack.firebasestorage.app',
    androidClientId: '745744612072-n62bkj6lrk9rnkfae1m93mtg6te9rol9.apps.googleusercontent.com',
    iosClientId: '745744612072-p7v694ftmceg7vnd6ejo040tqbopseei.apps.googleusercontent.com',
    iosBundleId: 'com.sirteefyapps.pairtrack',
  );
}
